### ISSUE TITLE
Reproduce

### ISSUE THREAD

**Issue by ductuantruong** [ItzJuny/CFPRF#1]
Hi,

Thank you for sharing your amazing work! This is definitely helpful for my research. However, I have a question about reproducing the result.

I can reproduce your result when using your provided checkpoints. However, when I re-trained and tested with my checkpoints, I could only obtain 9.76% EER (worse than your 7.41% EER). May I ask in your stage 2 training as well as the evaluation step,  did you perform the model's checkpoint average or just use the one checkpoint with the best devEER?

Thank you for your support!

**Comment by ItzJuny** [comment]
Hi ductuantruong,

Thank you for your interest in our work and I am glad to hear it has been helpful for your research.

Regarding your question on the training and evaluation process, we use the best-performing checkpoint based on the devEER for the second stage of training. To potentially enhance your results, you might want to use the following command for training on the PS dataset:

```python train_stage1.py --dn PS --v1 0.25 --v2 0.1 --num_epoch 18 --save```

Please note that discrepancies in results might also arise due to differences in the experimental setup and the GPU hardware used. I hope this information helps you achieve better results. Please feel free to reach out if you have further questions.

Thank you for your support!

**Comment by ductuantruong** [comment]
Hi @ItzJuny,

Thank you for your instant response! I also think the difference in performance comes from the mismatched GPU device since I followed your training script & code but didn't train the model on RTX3090 as yours. Can I ask one more question I know you used torch with cuda=11.1, but what is the cuda version on your computing machine?

Once again, thank you for your support!

**Comment by ItzJuny** [comment]
No problem at all, happy to help! Here's some key info about my pip environment that might be useful:

- python  3.8.0
- torch  1.8.1+cu111  
- torchaudio  0.8.1      
- torchvision  0.9.1+cu111       
- soundfile   0.11.0    
- librosa   0.9.1     
- fairseq  1.0.0a0 
- numpy  1.23.5

As for the platform:

- Driver Version: 470.182.03
- CUDA Version: 11.4
- GPU: One Single NVIDIA GeForce RTX 3090
- CPU: Intel Xeon Silver 4210R @ 2.40GHz

Hope that helps! Let me know if you have any more questions.

**Comment by ductuantruong** [comment]
Thank you for your great help! I'll update you when I get new results.

**Comment by Pengjie-W** [comment]
First of all, thank you for your open-source code. However, the metrics I obtained during the reproduction process also resulted in an EER of 9.76%.

**Comment by ductuantruong** [comment]
Hi @Pengjie-W ,

You could get a similar result to the one in the paper if you increase v1 to 0.45 (I got 7.62% EER) or if you have an RTX3090, you could obtain 7.50% EER (with v1=0.25 as the original code) when training with an RTX3090 GPU.

**Comment by Pengjie-W** [comment]
@ductuantruong Thank you for your reply.
I followed the hyperparameter settings from the original GitHub project and evaluated on the 3090 with the model at the lowest devEER and epoch 18 (.pth). I obtained EERs of 8.14% and 7.5%, respectively. I was very surprised to find that hardware had such a significant impact, which was quite shocking to me.
Additionally, I noticed that the hyperparameters in the code on GitHub differ greatly from those in the original paper, and I suspect that the performance variation might be due to these hyperparameter differences.
I will proceed with the hyperparameters you recommended for further experiments. Thank you.
